In [11]:
import pandas as pd
import numpy as np
from network import Network

## Data preparation ##

In [12]:
from sklearn.datasets import fetch_openml

# Fetch the MNIST dataset
mnist = fetch_openml('mnist_784', version=1)
x, y = mnist["data"], mnist["target"]

In [13]:
x =  x / 255
y = y.astype("int64")

In [14]:
x.head(10)

pixel1  pixel2  pixel3  pixel4  pixel5  pixel6  pixel7  pixel8  pixel9  \
0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
1     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
2     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
3     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
4     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
5     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
6     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
7     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
8     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
9     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   

   pixel10  ...  pixel775  pixel776  pixel777  pixel778  pixel779  pixel780  \
0      0.0  ...       0.0       0.0       0.0       0.0       0.0       0.0   
1      0.0  ...       0.0       0.0       0.0       0.0       0.0       0.0   
2      0.0  ...       0.0       0.0       0.0       0.0       0.0       0.0   
3      0.0  ...       0.0       0.0       0.0       0.0       0.0       0.0   
4      0.0  ...       0.0       0.0       0.0       0.0       0.0       0.0   
5      0.0  ...       0.0       0.0       0.0       0.0       0.0       0.0   
6      0.0  ...       0.0       0.0       0.0       0.0       0.0       0.0   
7      0.0  ...       0.0       0.0       0.0       0.0       0.0       0.0   
8      0.0  ...       0.0       0.0       0.0       0.0       0.0       0.0   
9      0.0  ...       0.0       0.0       0.0       0.0       0.0       0.0   

   pixel781  pixel782  pixel783  pixel784  
0       0.0       0.0       0.0       0.0  
1       0.0       0.0       0.0       0.0  
2       0.0       0.0       0.0       0.0  
3       0.0       0.0       0.0       0.0  
4       0.0       0.0       0.0       0.0  
5       0.0       0.0       0.0       0.0  
6       0.0       0.0       0.0       0.0  
7       0.0       0.0       0.0       0.0  
8       0.0       0.0       0.0       0.0  
9       0.0       0.0       0.0       0.0  

[10 rows x 784 columns]

In [15]:
data = pd.concat([x,y],axis=1)

In [16]:
data.head()

pixel1  pixel2  pixel3  pixel4  pixel5  pixel6  pixel7  pixel8  pixel9  \
0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
1     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
2     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
3     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
4     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   

   pixel10  ...  pixel776  pixel777  pixel778  pixel779  pixel780  pixel781  \
0      0.0  ...       0.0       0.0       0.0       0.0       0.0       0.0   
1      0.0  ...       0.0       0.0       0.0       0.0       0.0       0.0   
2      0.0  ...       0.0       0.0       0.0       0.0       0.0       0.0   
3      0.0  ...       0.0       0.0       0.0       0.0       0.0       0.0   
4      0.0  ...       0.0       0.0       0.0       0.0       0.0       0.0   

   pixel782  pixel783  pixel784  class  
0       0.0       0.0       0.0      5  
1       0.0       0.0       0.0      0  
2       0.0       0.0       0.0      4  
3       0.0       0.0       0.0      1  
4       0.0       0.0       0.0      9  

[5 rows x 785 columns]

In [17]:
randomized_data = data.sample(frac=1,random_state=42)

split_index = int(0.05 * len(randomized_data))

# Step 3: Split the DataFrame
train_data = randomized_data[:split_index]
test_data = randomized_data[split_index:]

train_x,train_y = train_data[["pixel"+str(i)for i in range(1,785)]],train_data["class"]
test_x,test_y = test_data[["pixel"+str(i)for i in range(1,785)]],test_data["class"]

## Experimenting ##

In [18]:
#create an instance of the network
nn = Network([784,10,10])

In [47]:
train_y = pd.get_dummies(train_y)
train_y = train_y.astype("int")
train_x,train_y = train_x.to_numpy(),train_y.to_numpy()
test_y = pd.get_dummies(test_y)
test_y = test_y.astype("int")
test_x,test_y = test_x.to_numpy(),test_y.to_numpy()

ValueError: Data must be 1-dimensional, got ndarray of shape (3500, 10) instead

In [20]:
nn.backpropagate(train_y.T,train_x.T)

epoch 0 | loss = 3.7488826875587717
epoch 1000 | loss = 0.19369045613818045
epoch 2000 | loss = 0.1278944542978103
epoch 3000 | loss = 0.09987994713386186


In [21]:
cc = nn.feed_forward(train_x.T)

In [43]:
def calculate_accuracy(actual, predicted):
    # For multi-class classification, you typically choose the class with the highest probability.
    predicted_classes = np.argmax(predicted, axis=0)
    actual_classes = np.argmax(actual, axis=0)
    print(actual_classes)
    # Compare predicted classes with actual classes
    correct_predictions = np.sum(predicted_classes == actual_classes)
    
    # Calculate accuracy as the ratio of correct predictions to total samples
    accuracy = correct_predictions / len(actual_classes)
    
    return accuracy


In [36]:
pp = nn.feed_forward(train_x.T)
print(round(calculate_accuracy(train_y.T,pp))*100,"%")

100 %


In [37]:
np.argmax(pp,axis=0)

array([8, 4, 8, ..., 7, 7, 2], dtype=int64)

In [38]:
np.argmax(train_y,axis=1)

array([8, 4, 8, ..., 7, 7, 2], dtype=int64)

In [39]:
jj = nn.feed_forward(test_x.T)
np.argmax(jj,axis=0)

array([0, 7, 3, ..., 1, 0, 0], dtype=int64)

In [46]:
test_y

49989    0
17969    7
2941     3
37347    2
1182     6
        ..
37194    6
6265     6
54886    1
860      0
15795    0
Name: class, Length: 66500, dtype: int64

In [44]:
calculate_accuracy(test_y.T,jj)

16


TypeError: object of type 'numpy.int64' has no len()